### PR TITLE
Signup and login functionality added

### PR DESCRIPTION
**Pull request by rajtheinnovator**
I've added the codes and now you'll need to setup Firebase by first signin in at [https://console.firebase.google.com](firebase console) and then creating a project. Finally you'll need to add Android app to it by getting the SHA-1 key from Android Studio as in the image at [https://github.com/rajtheinnovator/Popular-Movies/blob/27c63979e0634f48835989a27964d9331e519824/SHA.jpg](this link).

And then lastly, you'll download the google-services.json file from Firebase console and paste it directly inside the app folder of the project. Don't forget to enable Sign-In method through email/password in the console of Firebase.

### CODE REVIEW

**Comment by dharanad** [comment]
Thanks 👍

**Comment by dharanad** [comment]
@rajtheinnovator Sorry 😢  I merged it it but reverted it back. Can you make this changes in new branch and make a PR again.

**Comment by rajtheinnovator** [comment]
@dharan1011  now what we need to do is saving the movies to the database. Give it a try first and then let me know if any further help is needed. Meanwhile I'll improve the Javadoc as it's super important in a open-sourced project.

**Comment by dharanad** [comment]
@rajtheinnovator Can you implement the authentication in a new branch and make a PR.

**Pull request merged**
